import {loadContent} from "@/lib/store";
import {defaults,film} from "@/lib/content";
import {NewsCard,SupportBand,Unavailable} from "./ui";
import {Droplets,Leaf,Users,Play} from "lucide-react";
export const dynamic="force-dynamic";
export default async function Home(){const data=await loadContent().catch(()=>null);const s=data?.settings??defaults;return <>
<section className="hero"><div className="hero-image" style={s.hero?{backgroundImage:`url("${s.hero}")`}:undefined}/><div className="hero-shade"/><div className="container hero-content"><span className="eyebrow">Szeged–Kiskundorozsma · Öreghegy</span><h1>Vizet a tájba.<br/><em>Életet Öreghegyre.</em></h1><p>Egy kiszáradt szikes tórendszer új esélye.<br/>Helyi összefogással visszatartjuk a vizet,<br className="desktop"/> és segítjük az élőhelyek megújulását.</p><div className="actions"><a className="button lime" href="/projekt">Ismerd meg a projektet</a><a className="video-link" href={film} target="_blank" rel="noreferrer"><span><Play size={17}/></span> Nézd meg a kisfilmünket</a></div><div className="hero-caption">ÖREGHEGYI MINTAPROJEKT <span>Vízmegtartás · Élőhely-helyreállítás</span></div></div></section>
<section className="metrics"><div className="container metric-grid"><div><strong>30 <span>ha</span></strong><p>legnagyobb egyidejű vízborítás</p></div><div><strong>200 000<span>+ m³</span></strong><p>kivezetett víz az első ciklusban</p></div><div><strong>7</strong><p>vízpótlással érintett helyszín</p></div><div><strong>4,25 <span>km</span></strong><p>újra vízzel ellátott csatorna</p></div></div><div className="container source-note">A projekt 2026-os vezetői kivonatában dokumentált eredmények.</div></section>
<section className="container section story-grid"><div><span className="eyebrow">A táj emlékszik a vízre</span><h2>Ahol egykor tavak voltak,<br/>ott újra lehet élet.</h2></div><div className="prose"><p>Öreghegy régi tómedrei ma is őrzik a szikes vizes élőhelyek nyomait. A csatornák sokáig elvezették innen a vizet. Mi azt keressük, hogyan segíthetnek újra a táj vízellátásában.</p><p>A meglévő vízügyi rendszerre, részletes felmérésekre és az érintettek együttműködésére építünk. A cél a természetes vízjáráshoz igazodó, szezonális vízpótlás.</p><a className="text-link" href="/projekt">Így dolgozunk Öreghegyen</a></div></section>
<section className="values-section"><div className="container value-grid">{[[Droplets,"Megtartott víz","A megfelelő időben a megfelelő helyre vezetjük a vizet, és követjük a változásokat."],[Leaf,"Megújuló élőhely","A szikes táj sajátos élővilágát és az időszakosan vízjárta gyepeket segítjük."],[Users,"Helyi összefogás","Önkéntesek, gazdálkodók és szakemberek közös munkájára építünk."]].map(([Icon,title,text],i)=>{const I=Icon as typeof Droplets;return <div key={i}><I size={30} strokeWidth={1.4}/><h3>{title as string}</h3><p>{text as string}</p></div>})}</div></section>
<section className="container section"><div className="section-heading"><div><span className="eyebrow">Terepnapló</span><h2>Történetek a víz mellől.</h2></div><a className="text-link" href="/hirek">Minden hír</a></div>{data?<div className="news-grid">{data.entries.filter(x=>x.kind==="news").slice(0,2).map(x=><NewsCard key={x.id} entry={x}/>)}</div>:<Unavailable/>}</section><SupportBand/></>}
