export type Entry={id:string;kind:"news"|"photo";title:string;body:string;image:string;date:string;published:number;updated:string};
export type Settings={about:string;support:string;donationUrl:string;beneficiary:string;bankAccount:string;email:string;logo:string;hero:string;address:string;taxNumber:string;bankName:string;bankAddress:string;swift:string;hufIban:string;eurIban:string;usdIban:string};
export const defaults:Settings={
 about:"A Szegedi Vízőrzők önkéntes civil közössége azért dolgozik, hogy a víz újra helyet kapjon az alföldi tájban. Öreghegyen helyi tudás, természettudományos mérések és közös terepi munka találkozik.\n\nA csapatban projektkoordinációval, hidrogeológiával, térinformatikával, távérzékeléssel, botanikával, környezetvédelemmel és informatikával foglalkozó szakemberek dolgoznak együtt. A megvalósításhoz elengedhetetlen a földtulajdonosok, a gazdálkodók és az intézményi partnerek együttműködése.",
 support:"A folytatáshoz vízkormányzási eszközökre, terepi mérésekre és a mindennapi szervezőmunkához szükséges erőforrásokra van szükségünk. Pénzbeli támogatás, eszközfelajánlás és szakmai segítség egyaránt előreviszi a projektet.",
 donationUrl:"https://www.donably.com/szegedi-vizorzok",beneficiary:"Dél-Alföldi Vízőrzők Egyesület",bankAccount:"12067008-02221438-00100001",email:"",logo:"/images/logo-donably.png",hero:"/images/cover-donably.png",address:"6791 Szeged, Atracél köz 7.",taxNumber:"19445942-1-06",bankName:"Raiffeisen Bank Zrt.",bankAddress:"1133 Budapest, Váci út 116-118.",swift:"UBRTHUHB",hufIban:"HU16-12067008-02221438-00100001",eurIban:"HU16-12067008-02221438-00200008",usdIban:"HU92-12067008-02221438-00300005"
};
export const initialEntries:Entry[]=[
 {id:"terepi-kozos-munka",kind:"photo",title:"Közös terepi munka",body:"A vízpótláshoz szükséges eszközök előkészítése. Fotó: Szegedi Vízőrzők; forrás: Greendex.",image:"/images/siphon-greendex.webp",date:"2026-09-09",published:1,updated:"2026-09-09"},
 {id:"szivornya-a-terepen",kind:"photo",title:"Vízpótlás szivornyával",body:"Gravitációs vízkivezetés a projektterületen. Fotó: Szegedi Vízőrzők; forrás: Greendex.",image:"/images/field-greendex.webp",date:"2026-09-09",published:1,updated:"2026-09-09"},
 {id:"viz-az-elohelyen",kind:"photo",title:"Víz az élőhelyen",body:"Újra víz a növényzet között. Fotó: Szegedi Vízőrzők; forrás: Greendex.",image:"/images/life-greendex.webp",date:"2026-09-09",published:1,updated:"2026-09-09"},
 {id:"elso-vizpotlasi-ciklus",kind:"news",title:"Újra víz került az öreghegyi tómedrekbe",body:"A 2026. február 8-án indult próbatöltés során a meglévő csatornákat, átereszeket és vízkormányzó műtárgyakat használtuk. A vízpótlás gravitációs úton, szivornyákkal történt.\n\nAz első ciklusban több mint 200 000 köbméter vizet vezettünk ki. A vízborítás egyidejű legnagyobb kiterjedése 30 hektár volt, hét helyszínen. A beszámoló szerint 4,25 kilométernyi korábban száraz csatornaszakasz kapott vizet.\n\nA változásokat vízmércékkel, terepi felmérésekkel, műholdfelvételekkel és ökológiai megfigyelésekkel követjük. A talajvízre gyakorolt teljes hatás kiértékelése még folyamatban van.\n\nForrás: Szegedi Vízőrzők, Öreghegy Mintaprojekt vezetői kivonat; 2026.",image:"/images/siphon-greendex.webp",date:"2026-09-09",published:1,updated:"2026-09-09"},
 {id:"meresek-es-elohelyek",kind:"news",title:"A víz mellett az élőhely változását is figyeljük",body:"A vízpótlást követően vizes élőhelyekhez kötődő növények és állatok megjelenését dokumentáltuk. A sziki lebegőkandics tömeges jelenléte a szikes élőhelyek megfigyelésének egyik érdekes eredménye.\n\nA botanikai felmérések a szikfok- és mocsári növényzet állapotát rögzítik. A terepi megfigyeléseket műholdas vegetációs adatokkal és talajvízmérésekkel kapcsoljuk össze.\n\nAz első eredmények biztatóak. A tartós ökológiai hatások értékeléséhez hosszabb adatsorra és további mintavételekre van szükség.\n\nForrás: Szegedi Vízőrzők, Öreghegy Mintaprojekt vezetői kivonat; 2026.",image:"/images/life-greendex.webp",date:"2026-09-09",published:1,updated:"2026-09-09"}
];
export const facebook="https://www.facebook.com/szegedi.vizorzok/";
export const film="https://www.youtube.com/watch?v=O8Q1IFrXWtM";
export function dateLabel(d:string){return new Date(d+"T12:00:00").toLocaleDateString("hu-HU",{year:"numeric",month:"long",day:"numeric"})}
