import {isAdmin,sameOrigin} from "@/lib/admin";import {database,loadContent} from "@/lib/store";import {defaults} from "@/lib/content";import {z} from "zod";
const imagePath=z.string().max(300).refine(s=>s===""||/^\/(images\/[a-zA-Z0-9._-]+|api\/media\/[a-f0-9-]+\.(png|jpg|webp))$/.test(s));
const entry=z.object({id:z.string().regex(/^[a-z0-9-]{1,100}$/),kind:z.enum(["news","photo"]),title:z.string().trim().min(1).max(160),body:z.string().max(50000),image:imagePath,date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!isNaN(Date.parse(s))),published:z.union([z.literal(0),z.literal(1)])}).refine(e=>e.kind!=="photo"||e.image!=="",{message:"A galériabejegyzéshez képet is fel kell tölteni."});
const config=z.object(Object.fromEntries(Object.keys(defaults).map(k=>[k,z.string().max(k==="about"||k==="support"?15000:400)]))) as z.ZodType<Record<string,string>>;
function error(message:string,status=400){return Response.json({error:message},{status})}
export async function GET(){if(!await isAdmin())return error("Nincs szerkesztői jogosultság.",403);try{return Response.json(await loadContent(true),{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return error("Az adattár nem érhető el.",503)}}
export async function POST(req:Request){if(!await isAdmin())return error("Nincs szerkesztői jogosultság.",403);if(!sameOrigin(req))return error("Érvénytelen kérés.",403);if(Number(req.headers.get("content-length")||0)>150000)return error("Túl nagy tartalom.",413);try{const input=z.object({action:z.string(),entry:z.unknown().optional(),settings:z.unknown().optional()}).parse(await req.json());const db=database();
 if(input.action==="entry"){const e=entry.parse(input.entry);await db.prepare("INSERT INTO entries (id,kind,title,body,image,date,published,updated) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,title=excluded.title,body=excluded.body,image=excluded.image,date=excluded.date,published=excluded.published,updated=excluded.updated").bind(e.id,e.kind,e.title,e.body,e.image,e.date,e.published,new Date().toISOString()).run();return Response.json({ok:true,id:e.id});}
 if(input.action==="settings"){const s=config.parse(input.settings);imagePath.parse(s.logo);imagePath.parse(s.hero);if(s.donationUrl){const u=new URL(s.donationUrl);if(u.protocol!=="https:")return error("HTTPS támogatási linket adj meg.");}if(s.email&&!z.string().email().safeParse(s.email).success)return error("Érvénytelen e-mail-cím.");await db.prepare("INSERT INTO settings (id,value) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind("site",JSON.stringify(s)).run();return Response.json({ok:true});}
 return error("Ismeretlen művelet.");
 }catch(e){if(e instanceof z.ZodError)return error(e.issues[0]?.message??"Ellenőrizd a mezőket.");console.error("Save failed",e);return error("A mentés nem sikerült. A beírt tartalom megmaradt; próbáld újra.",503)}}
